/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Device {
  'id' : bigint,
  'status' : string,
  'temperature' : bigint,
  'isOn' : boolean,
  'name' : string,
  'brightness' : bigint,
  'deviceType' : DeviceType,
  'roomId' : bigint,
}
export type DeviceType = { 'fan' : null } |
  { 'plug' : null } |
  { 'light' : null } |
  { 'thermostat' : null } |
  { 'blind' : null } |
  { 'camera' : null };
export interface Room { 'id' : bigint, 'icon' : string, 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDevice' : ActorMethod<[bigint, string, DeviceType], Device>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createRoom' : ActorMethod<[string, string], Room>,
  'deleteRoom' : ActorMethod<[bigint], undefined>,
  'getAllDevices' : ActorMethod<[], Array<Device>>,
  'getAllRooms' : ActorMethod<[], Array<Room>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDevice' : ActorMethod<[bigint], Device>,
  'getRoom' : ActorMethod<[bigint], Room>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'updateDeviceState' : ActorMethod<[bigint, boolean, bigint, bigint], Device>,
  'updateRoom' : ActorMethod<[bigint, string, string], Room>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];