/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DeviceType = IDL.Variant({
  'fan' : IDL.Null,
  'plug' : IDL.Null,
  'light' : IDL.Null,
  'thermostat' : IDL.Null,
  'blind' : IDL.Null,
  'camera' : IDL.Null,
});
export const Device = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'temperature' : IDL.Nat,
  'isOn' : IDL.Bool,
  'name' : IDL.Text,
  'brightness' : IDL.Nat,
  'deviceType' : DeviceType,
  'roomId' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Room = IDL.Record({
  'id' : IDL.Nat,
  'icon' : IDL.Text,
  'name' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDevice' : IDL.Func([IDL.Nat, IDL.Text, DeviceType], [Device], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createRoom' : IDL.Func([IDL.Text, IDL.Text], [Room], []),
  'deleteRoom' : IDL.Func([IDL.Nat], [], []),
  'getAllDevices' : IDL.Func([], [IDL.Vec(Device)], ['query']),
  'getAllRooms' : IDL.Func([], [IDL.Vec(Room)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDevice' : IDL.Func([IDL.Nat], [Device], ['query']),
  'getRoom' : IDL.Func([IDL.Nat], [Room], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'updateDeviceState' : IDL.Func(
      [IDL.Nat, IDL.Bool, IDL.Nat, IDL.Nat],
      [Device],
      [],
    ),
  'updateRoom' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [Room], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DeviceType = IDL.Variant({
    'fan' : IDL.Null,
    'plug' : IDL.Null,
    'light' : IDL.Null,
    'thermostat' : IDL.Null,
    'blind' : IDL.Null,
    'camera' : IDL.Null,
  });
  const Device = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'temperature' : IDL.Nat,
    'isOn' : IDL.Bool,
    'name' : IDL.Text,
    'brightness' : IDL.Nat,
    'deviceType' : DeviceType,
    'roomId' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Room = IDL.Record({
    'id' : IDL.Nat,
    'icon' : IDL.Text,
    'name' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDevice' : IDL.Func([IDL.Nat, IDL.Text, DeviceType], [Device], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createRoom' : IDL.Func([IDL.Text, IDL.Text], [Room], []),
    'deleteRoom' : IDL.Func([IDL.Nat], [], []),
    'getAllDevices' : IDL.Func([], [IDL.Vec(Device)], ['query']),
    'getAllRooms' : IDL.Func([], [IDL.Vec(Room)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDevice' : IDL.Func([IDL.Nat], [Device], ['query']),
    'getRoom' : IDL.Func([IDL.Nat], [Room], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'updateDeviceState' : IDL.Func(
        [IDL.Nat, IDL.Bool, IDL.Nat, IDL.Nat],
        [Device],
        [],
      ),
    'updateRoom' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [Room], []),
  });
};

export const init = ({ IDL }) => { return []; };