/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Room {
    id: bigint;
    icon: string;
    name: string;
}
export interface Device {
    id: bigint;
    status: string;
    temperature: bigint;
    isOn: boolean;
    name: string;
    brightness: bigint;
    deviceType: DeviceType;
    roomId: bigint;
}
export enum DeviceType {
    fan = "fan",
    plug = "plug",
    light = "light",
    thermostat = "thermostat",
    blind = "blind",
    camera = "camera"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addDevice(roomId: bigint, name: string, deviceType: DeviceType): Promise<Device>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createRoom(name: string, icon: string): Promise<Room>;
    deleteRoom(id: bigint): Promise<void>;
    getAllDevices(): Promise<Array<Device>>;
    getAllRooms(): Promise<Array<Room>>;
    getCallerUserRole(): Promise<UserRole>;
    getDevice(id: bigint): Promise<Device>;
    getRoom(id: bigint): Promise<Room>;
    isCallerAdmin(): Promise<boolean>;
    updateDeviceState(id: bigint, isOn: boolean, brightness: bigint, temperature: bigint): Promise<Device>;
    updateRoom(id: bigint, name: string, icon: string): Promise<Room>;
}
import type { Device as _Device, DeviceType as _DeviceType, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addDevice(arg0: bigint, arg1: string, arg2: DeviceType): Promise<Device> {
        if (this.processError) {
            try {
                const result = await this.actor.addDevice(arg0, arg1, to_candid_DeviceType_n1(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Device_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDevice(arg0, arg1, to_candid_DeviceType_n1(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Device_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createRoom(arg0: string, arg1: string): Promise<Room> {
        if (this.processError) {
            try {
                const result = await this.actor.createRoom(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRoom(arg0, arg1);
            return result;
        }
    }
    async deleteRoom(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRoom(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRoom(arg0);
            return result;
        }
    }
    async getAllDevices(): Promise<Array<Device>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDevices();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDevices();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRooms(): Promise<Array<Room>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRooms();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRooms();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDevice(arg0: bigint): Promise<Device> {
        if (this.processError) {
            try {
                const result = await this.actor.getDevice(arg0);
                return from_candid_Device_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDevice(arg0);
            return from_candid_Device_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRoom(arg0: bigint): Promise<Room> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoom(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoom(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async updateDeviceState(arg0: bigint, arg1: boolean, arg2: bigint, arg3: bigint): Promise<Device> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDeviceState(arg0, arg1, arg2, arg3);
                return from_candid_Device_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDeviceState(arg0, arg1, arg2, arg3);
            return from_candid_Device_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateRoom(arg0: bigint, arg1: string, arg2: string): Promise<Room> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRoom(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRoom(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_DeviceType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DeviceType): DeviceType {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Device_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Device): Device {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: string;
    temperature: bigint;
    isOn: boolean;
    name: string;
    brightness: bigint;
    deviceType: _DeviceType;
    roomId: bigint;
}): {
    id: bigint;
    status: string;
    temperature: bigint;
    isOn: boolean;
    name: string;
    brightness: bigint;
    deviceType: DeviceType;
    roomId: bigint;
} {
    return {
        id: value.id,
        status: value.status,
        temperature: value.temperature,
        isOn: value.isOn,
        name: value.name,
        brightness: value.brightness,
        deviceType: from_candid_DeviceType_n5(_uploadFile, _downloadFile, value.deviceType),
        roomId: value.roomId
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fan: null;
} | {
    plug: null;
} | {
    light: null;
} | {
    thermostat: null;
} | {
    blind: null;
} | {
    camera: null;
}): DeviceType {
    return "fan" in value ? DeviceType.fan : "plug" in value ? DeviceType.plug : "light" in value ? DeviceType.light : "thermostat" in value ? DeviceType.thermostat : "blind" in value ? DeviceType.blind : "camera" in value ? DeviceType.camera : value;
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Device>): Array<Device> {
    return value.map((x)=>from_candid_Device_n3(_uploadFile, _downloadFile, x));
}
function to_candid_DeviceType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DeviceType): _DeviceType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DeviceType): {
    fan: null;
} | {
    plug: null;
} | {
    light: null;
} | {
    thermostat: null;
} | {
    blind: null;
} | {
    camera: null;
} {
    return value == DeviceType.fan ? {
        fan: null
    } : value == DeviceType.plug ? {
        plug: null
    } : value == DeviceType.light ? {
        light: null
    } : value == DeviceType.thermostat ? {
        thermostat: null
    } : value == DeviceType.blind ? {
        blind: null
    } : value == DeviceType.camera ? {
        camera: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
